### ISSUE TITLE
opencv.VideoCapture() not compatible with libcamera

### ISSUE THREAD

**Issue by k323r** [flucto-gmbh/motion-sensor-box#107]
examples of how to get video frames captured via picamera2 into opencv: https://github.com/raspberrypi/picamera2/tree/main/examples/tensorflow

**Comment by k323r** [comment]
Fixed it,

**Comment by k323r** [comment]
Waiting on pull request

**Comment by pacjac** [comment]
Closing, fixed in #124, a re-submission of #114.
