### ISSUE TITLE
Update csv header with physical units

### ISSUE THREAD

**Issue by dfeldmann** [flucto-gmbh/motion-sensor-box#118]
The header of the csv output file should contain more information about the data being stored. For example the unit of the acceleration; is it in meter per second squared or in multiples of g...?

**Comment by k323r** [comment]
this is difficult to implement as the csv header is also used as a list of keys to access received json records in the fusionlog service. as we are sunsetting the fusionlog service in favour of the much less load-intensive rawlogger, i'm closing this issue.
