### ISSUE TITLE
Add an ethernet socket?

### ISSUE THREAD

**Issue by ahaselsteiner** [flucto-gmbh/motion-sensor-box#33]
We discussed adding an ethernet socket to MSB.

Pros:
 - Was required to integrate ZX Lidar 
 - WLAN is flaky, for reliable accessing MSB ethernet could be helpful (we also discussed bluetooth for this issue)

Cons:
 - Another part --> MSB becomes more expensive (bill of material + assembly)
 - Aother part and feature --> MSB becomes more complex

**Comment by k323r** [comment]
Ethernet socket has been added in revision B.
