### ISSUE TITLE
msb_broker print_stdout not working

### ISSUE THREAD

**Issue by k323r** [flucto-gmbh/motion-sensor-box#50]
when running msb_broker.py with the --print-stout flag, an exceptio is thrown: the flag is not implemented

**Comment by pacjac** [comment]
Is this still relevant @k323r ?

**Comment by k323r** [comment]
This is not relevant anymore and also not possible to implement, as the traffic between the two sockets is encapsulated by the call to zmq.proxy and hence cannot be published to stdout. closing.
