### ISSUE TITLE
Reimplement attitude service

### ISSUE THREAD

**Issue by pacjac** [flucto-gmbh/motion-sensor-box#54]
- [ ] Evaluate algorithms  
- [ ] Evaluate AHRS library: Data Streams? Performance? 
- [ ] Generate test data set

**Comment by pacjac** [comment]
See #38

**Comment by k323r** [comment]
@kawindme As mentioned in #26 , the imu features a digital motion processor, that should - in theory - be able to provide a orientation quaternion out of the box. The issue with this feature is, that the attitude estimation is done by a fpga, whose firmware is a proprietary, binay blob that is tedious to flash onto the imu. There are some examples out there of people, that have gotten it to work. Might be worth it to investigate.

**Comment by k323r** [comment]
msb_attitude has been reimplemented with a complementary filter in #123
