### ISSUE TITLE
GPS and gpsd

### ISSUE THREAD

**Issue by pacjac** [flucto-gmbh/motion-sensor-box#55]
Documentation and code feature workarounds for gpsd library (see doc/dependencies/gpsd) 
and python gps library 

```
GPS_DIR = '/usr/local/lib/python3/dist-packages/'
if not os.path.isdir(os.path.join(GPS_DIR, 'gps')):
    raise Exception(f'no such file or directory: {GPS_DIR/gps}')
sys.path.append(os.path.dirname(GPS_DIR))
```

is this still required? With the currently distributed version 3.22 [apt link](https://packages.debian.org/search?searchon=names&keywords=gpsd) that comes with debian bullseye?

- [ ] Fix documentation
- [ ] Fix code

**Comment by k323r** [comment]
msb_now working with system-supplied gpsd and gpsd socket.
