### ISSUE TITLE
gpsd submodule in lib directory not properly linked

### ISSUE THREAD

**Issue by kawindme** [flucto-gmbh/motion-sensor-box#58]

**Comment by k323r** [comment]
So, I think we are deprecating the gpsd submodule in favor of the gpsd version that is now supplied through the official sources. In 2021, the gpsd version that was supplied with raspberry pi os (ne raspbian) was too old. By now, raspberry pi os has catched up and we can remove the submodule.

**Comment by k323r** [comment]
fixed it
